#!/bin/bash

set -x

mkdir -p ~/.vim/{autoload,bundle}
python2 -c "import urllib, os;\
    print urllib.urlretrieve('https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim', \
    os.path.join(os.path.expanduser('~'), '.vim', 'autoload', 'pathogen.vim'))"

git clone git://github.com/nvie/vim-flake8.git /tmp/vim-flake8-$$
cp -r /tmp/vim-flake8-$$/ftplugin ~/.vim/ftplugin/

set +x
