#!/bin/bash

set -x
CMD=virtualenv
if [ ! -e ~/python2 ]; then
    if (which $CMD 2>&1>/dev/null); then
         $CMD ~/python2
         source ~/python2/bin/activate
         pip install -r ~/.py2req.txt
    else
        echo "Missing $CMD"; exit 1
    fi
else
  echo ~/python2 exists
fi
set +x
